// ─────────────────────────────────────────────────────────────────────
// CDDAL export (TODO.reconfigure/04, "CDDAL interop"): the dictionary
// subset of a Primmel package projected into the CDD Authoring Language
// (opencdd/cddal-spec) for interop with the OpenCDD toolchain.
//
// The projection is POWER-TYPED, because CDD has no separate
// instance-entity: an individual is a subclass-of-one. The mapping:
//
//   class C { a, b }              →  instance C < MDC_C002 {
//                                       code: C
//                                       superclass: UNIVERSE   // or `extends`
//                                       applicable_properties: { a, b }
//                                     }
//   instance s of C { a: 2.2 t }  →  instance s < MDC_C002 {
//                                       code: s
//                                       superclass: C          // the `of`
//                                       a: "2.2 t"
//                                     }
//
// Every Primmel identifier survives verbatim (the class id, the
// instance id, the field ids); every exhibited value rides as a
// property assignment; the instance's `of` rides as the CDD
// superclass — the round-trip stability requirement (cddal-spec
// clause 11; kernel rule R5) holds with no exceptions on this subset.
//
// Deliberately out of the first slice, each a carried work item:
// attribute definitions as MDC_C003 property entities (with the IRDI
// where the definition declares `corresponds`), enums as value lists,
// multilingual definitions beyond the default language tag, and
// package includes as CDDAL imports.
//
// ONE-WAY lossy projection like every interop projection: the CDDAL
// text is generated, never authored, never re-imported as truth.
// ─────────────────────────────────────────────────────────────────────

import { loadPackage } from '../ser-des/package';
import { basename, resolve } from 'node:path';
import type Standard from '../types/Standard';
import type { QuantityValue } from '../types/Quantity';

export const CDDAL_PROJECTION_VERSION = 'primmel-cddal/1';

export interface CddalExportStats {
  /** Classes projected as class entities (instances of MDC_C002). */
  classes: number;
  /** Instances projected as subclass-of-one class entities. */
  instances: number;
  /** Property assignments emitted (exhibited values). */
  assignments: number;
}

export interface CddalExport {
  version: typeof CDDAL_PROJECTION_VERSION;
  cddal: string;
  stats: CddalExportStats;
}

function escapeCddalString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function quote(s: string): string {
  return `"${escapeCddalString(s)}"`;
}

/** A CDDAL identifier is [A-Za-z0-9_]; Primmel ids also carry hyphens
 *  and dots (smp-hbk-hlci-001, ref derives URNs). The NAME slot of an
 *  instance declaration must be a plain identifier, so a Primmel id
 *  rides there sanitized — the VERBATIM id rides the `code:` assignment
 *  (quoted when unsafe), which cddal-spec clause 11 names as the
 *  round-trip identity ("the same IRDI, code, and meta-class
 *  membership"). */
function safeSymbol(id: string): string {
  const s = id.replace(/[^A-Za-z0-9_]+/g, '_');
  return /^[0-9]/.test(s) ? `N${s}` : s;
}

function isSafeIdentifier(id: string): boolean {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(id);
}

/** A code assignment: the verbatim Primmel id. */
function codeAssignment(id: string): string {
  return isSafeIdentifier(id) ? id : quote(id);
}

/** A quantity assignment: the value with its unit, one token pair. */
function quantity(v: QuantityValue): string {
  return quote(
    v.unit !== undefined && v.unit !== ''
      ? `${v.value} ${v.unit}`
      : String(v.value),
  );
}

export function projectCddal(model: Standard, packageId: string): CddalExport {
  const lines: string[] = [
    `# ${CDDAL_PROJECTION_VERSION} — the dictionary subset of ${packageId}`,
    '# (generated by primmel export cddal — never authored, never re-imported)',
    '',
  ];
  const stats: CddalExportStats = { classes: 0, instances: 0, assignments: 0 };

  for (const c of model.dataclasses) {
    stats.classes++;
    lines.push(`instance ${safeSymbol(c.id)} < MDC_C002 {`);
    lines.push(`  code: ${codeAssignment(c.id)}`);
    if (c.description) {
      lines.push(`  definition.en: ${quote(c.description)}`);
    }
    lines.push(
      `  superclass: ${c.extends !== undefined ? safeSymbol(c.extends) : 'UNIVERSE'}`,
    );
    if (c.attributes.length > 0) {
      lines.push(
        `  applicable_properties: { ${c.attributes.map(a => safeSymbol(a.id)).join(', ')} }`,
      );
    }
    lines.push('}');
    lines.push('');
  }

  for (const inst of model.instances) {
    stats.instances++;
    lines.push(`instance ${safeSymbol(inst.id)} < MDC_C002 {`);
    lines.push(`  code: ${codeAssignment(inst.id)}`);
    if (inst.of) {
      lines.push(`  superclass: ${safeSymbol(inst.of)}`);
    }
    for (const [id, v] of Object.entries(inst.has?.attributes ?? {})) {
      stats.assignments++;
      lines.push(`  ${safeSymbol(id)}: ${quantity(v)}`);
    }
    lines.push('}');
    lines.push('');
  }

  if (stats.classes === 0 && stats.instances === 0) {
    throw new Error(
      'no dictionary content: the CDDAL projection carries classes and instances',
    );
  }

  return {
    version: CDDAL_PROJECTION_VERSION,
    cddal: lines.join('\n'),
    stats,
  };
}

export function exportPackageCddal(dir: string): CddalExport {
  return projectCddal(loadPackage(dir), basename(resolve(dir)));
}
